import React, { useState } from 'react';
import { EngineeringBlueprint } from '../types';
import {
  FileText,
  Database,
  Server,
  Layers,
  Lock,
  Zap,
  Cpu,
  Calendar,
  Check,
  Copy,
  Download,
} from 'lucide-react';

interface BlueprintViewerProps {
  blueprint: EngineeringBlueprint;
  domain: string;
}

export const BlueprintViewer: React.FC<BlueprintViewerProps> = ({ blueprint, domain }) => {
  const [activeBlueprintTab, setActiveBlueprintTab] = useState<
    'overview' | 'database' | 'api' | 'auth' | 'caching' | 'phases' | 'scalability'
  >('overview');

  const [copiedSql, setCopiedSql] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  // Generate complete SQL script for copy
  const generateSqlDdl = () => {
    return blueprint.databaseEntities
      .map((entity) => {
        const fields = entity.fields
          .map(
            (f) =>
              `  ${f.name.padEnd(24)} ${f.type.padEnd(16)} ${f.isPrimary ? 'PRIMARY KEY' : ''} ${
                f.references ? `REFERENCES ${f.references}` : ''
              }`.trimEnd()
          )
          .join(',\n');

        const indexes = entity.indexes.join('\n');
        return `-- Table: ${entity.name} (${entity.description})\nCREATE TABLE ${entity.name} (\n${fields}\n);\n\n${indexes}\n`;
      })
      .join('\n-----------------------------------------\n\n');
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(generateSqlDdl());
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  const handleExportMarkdown = () => {
    const md = `# Engineering Architecture Blueprint for ${domain}
Generated by StackLens Inspector

## 1. System Architecture Overview
${blueprint.overview}

- Architecture Pattern: ${blueprint.architecturePattern}
- Target Scale: ${blueprint.targetScale}

## 2. Production Tech Stack
- Frontend: ${blueprint.recommendedStack.frontend}
- Backend: ${blueprint.recommendedStack.backend}
- Primary Database: ${blueprint.recommendedStack.database}
- Caching: ${blueprint.recommendedStack.caching}
- Async Queue: ${blueprint.recommendedStack.queue}
- Infrastructure: ${blueprint.recommendedStack.infrastructure}
- Authentication: ${blueprint.recommendedStack.auth}
- Observability: ${blueprint.recommendedStack.observability}

## 3. Database Schema (PostgreSQL DDL)
\`\`\`sql
${generateSqlDdl()}
\`\`\`

## 4. API Endpoint Contracts
${blueprint.apiEndpoints.map((ep) => `### ${ep.method} ${ep.path}\n${ep.description}\n`).join('\n')}

## 5. Authentication Protocol
${blueprint.authStrategy.method}
${blueprint.authStrategy.flowDescription}

## 6. Implementation Roadmap
${blueprint.implementationPhases
  .map(
    (p) =>
      `### Phase ${p.phaseNumber}: ${p.title} (${p.duration})\nDeliverables:\n${p.deliverables
        .map((d) => `- ${d}`)
        .join('\n')}\nMilestone: ${p.milestone}\n`
  )
  .join('\n')}
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `StackLens-Blueprint-${domain.replace(/[^a-z0-9]/gi, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  return (
    <div className="w-full bg-[#161b22] border border-[#30363d] rounded-lg p-4 sm:p-5">
      {/* Blueprint Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 pb-3 border-b border-[#30363d]">
        <div>
          <div className="flex items-center space-x-2">
            <FileText className="w-4 h-4 text-[#58a6ff]" />
            <h3 className="text-sm font-semibold text-[#f0f6fc]">
              Build-from-Scratch Engineering Blueprint
            </h3>
            <span className="px-1.5 py-0.2 text-[10px] font-mono rounded bg-[#21262d] text-[#8b949e] border border-[#30363d]">
              {domain}
            </span>
          </div>
          <p className="text-xs text-[#8b949e] mt-0.5">
            Technical architecture specification, normalized relational schema, API contracts, and implementation phases.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center space-x-2">
          <button
            onClick={handleExportMarkdown}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded bg-[#21262d] hover:bg-[#30363d] text-[#f0f6fc] border border-[#30363d] text-xs font-mono transition-colors"
          >
            {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-[#3fb950]" /> : <Download className="w-3.5 h-3.5 text-[#58a6ff]" />}
            <span>{copiedMarkdown ? 'Exported' : 'Export .md'}</span>
          </button>
        </div>
      </div>

      {/* Navigation Sub-Tabs */}
      <div className="flex items-center gap-1 overflow-x-auto py-2.5 border-b border-[#30363d] scrollbar-none text-xs font-mono">
        <button
          onClick={() => setActiveBlueprintTab('overview')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'overview'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>1. Architecture &amp; Stack</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('database')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'database'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Database className="w-3.5 h-3.5" />
          <span>2. Database Schema ({blueprint.databaseEntities.length})</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('api')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'api'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Server className="w-3.5 h-3.5" />
          <span>3. API Contracts ({blueprint.apiEndpoints.length})</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('auth')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'auth'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Lock className="w-3.5 h-3.5" />
          <span>4. Auth Protocol</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('caching')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'caching'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Zap className="w-3.5 h-3.5" />
          <span>5. Caching &amp; Queues</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('phases')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'phases'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Calendar className="w-3.5 h-3.5" />
          <span>6. Phased Roadmap</span>
        </button>

        <button
          onClick={() => setActiveBlueprintTab('scalability')}
          className={`flex items-center space-x-1.5 px-2.5 py-1 rounded whitespace-nowrap transition-colors ${
            activeBlueprintTab === 'scalability'
              ? 'bg-[#21262d] text-[#f0f6fc] border border-[#30363d]'
              : 'text-[#8b949e] hover:text-[#f0f6fc]'
          }`}
        >
          <Cpu className="w-3.5 h-3.5" />
          <span>7. Scalability</span>
        </button>
      </div>

      {/* Tab 1: Architecture & Stack */}
      {activeBlueprintTab === 'overview' && (
        <div className="mt-4 space-y-4">
          <div className="p-3 rounded bg-[#0d1117] border border-[#30363d] text-xs text-[#c9d1d9] leading-relaxed">
            <strong className="text-[#f0f6fc] font-mono">System Architecture Summary: </strong>
            <span>{blueprint.overview}</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2.5">
            {Object.entries(blueprint.recommendedStack).map(([layer, tech]) => (
              <div key={layer} className="bg-[#0d1117] p-3 rounded border border-[#30363d] flex flex-col justify-between">
                <div>
                  <span className="text-[10px] font-mono uppercase font-semibold text-[#58a6ff]">{layer}</span>
                  <div className="text-xs font-semibold text-[#f0f6fc] mt-0.5 font-mono">{tech}</div>
                </div>
                <div className="mt-2 text-[10px] text-[#6e7681] font-mono">Production Tier</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab 2: Database Schema & SQL DDL */}
      {activeBlueprintTab === 'database' && (
        <div className="mt-4 space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono text-[#8b949e]">
              Normalized PostgreSQL Entities ({blueprint.databaseEntities.length} Tables)
            </span>

            <button
              onClick={handleCopySql}
              className="flex items-center space-x-1 px-2.5 py-1 rounded bg-[#21262d] hover:bg-[#30363d] text-[#f0f6fc] border border-[#30363d] text-xs font-mono transition-colors"
            >
              {copiedSql ? <Check className="w-3 h-3 text-[#3fb950]" /> : <Copy className="w-3 h-3 text-[#58a6ff]" />}
              <span>{copiedSql ? 'Copied' : 'Copy DDL'}</span>
            </button>
          </div>

          <div className="space-y-3.5">
            {blueprint.databaseEntities.map((entity) => (
              <div key={entity.name} className="bg-[#0d1117] rounded border border-[#30363d] overflow-hidden">
                <div className="p-2.5 bg-[#161b22] border-b border-[#30363d] flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                  <div className="flex items-center space-x-2">
                    <span className="font-mono font-bold text-xs text-[#58a6ff]">TABLE {entity.name}</span>
                    <span className="px-1.5 py-0.2 text-[9px] rounded bg-[#21262d] text-[#8b949e] font-mono">
                      {entity.estimatedVolume}
                    </span>
                  </div>
                  <p className="text-[11px] text-[#8b949e]">{entity.description}</p>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-[#0d1117] text-[#8b949e] border-b border-[#21262d] font-mono text-[10px]">
                      <tr>
                        <th className="p-2 w-1/4">Field</th>
                        <th className="p-2 w-1/5">Type</th>
                        <th className="p-2 w-1/4">Constraints</th>
                        <th className="p-2">Description</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-[#21262d] font-mono text-slate-300 text-[11px]">
                      {entity.fields.map((field) => (
                        <tr key={field.name} className="hover:bg-[#161b22]/50">
                          <td className="p-2 font-semibold text-[#f0f6fc] flex items-center space-x-1.5">
                            <span>{field.name}</span>
                            {field.isPrimary && (
                              <span className="px-1 py-0.2 rounded text-[8px] bg-[#4d2d00] text-[#d29922]">
                                PK
                              </span>
                            )}
                            {field.isForeign && (
                              <span className="px-1 py-0.2 rounded text-[8px] bg-[#1f6feb]/20 text-[#58a6ff]">
                                FK
                              </span>
                            )}
                          </td>
                          <td className="p-2 text-[#58a6ff]">{field.type}</td>
                          <td className="p-2 text-[#8b949e] text-[10px]">
                            {field.isPrimary ? 'PRIMARY KEY' : field.references ? `REF ${field.references}` : 'NOT NULL'}
                          </td>
                          <td className="p-2 text-[#8b949e] font-sans text-xs">{field.description}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {entity.indexes && entity.indexes.length > 0 && (
                  <div className="p-2 bg-[#161b22]/60 border-t border-[#21262d] text-[10px] font-mono text-[#8b949e]">
                    <span className="text-[#6e7681]">Indexes: </span>
                    {entity.indexes.join(' ')}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab 3: API Specification */}
      {activeBlueprintTab === 'api' && (
        <div className="mt-4 space-y-3">
          {blueprint.apiEndpoints.map((ep, idx) => (
            <div key={idx} className="bg-[#0d1117] rounded border border-[#30363d] p-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5 pb-2 border-b border-[#21262d]">
                <div className="flex items-center space-x-2">
                  <span
                    className={`px-1.5 py-0.2 rounded text-[10px] font-mono font-bold ${
                      ep.method === 'GET'
                        ? 'bg-[#1f6feb]/20 text-[#58a6ff]'
                        : ep.method === 'POST'
                        ? 'bg-[#1b4728] text-[#3fb950]'
                        : ep.method === 'DELETE'
                        ? 'bg-[#4d1f24] text-[#f85149]'
                        : 'bg-[#4d2d00] text-[#d29922]'
                    }`}
                  >
                    {ep.method}
                  </span>
                  <span className="font-mono text-xs font-semibold text-[#f0f6fc]">{ep.path}</span>
                </div>

                <div>
                  {ep.authRequired ? (
                    <span className="px-1.5 py-0.2 rounded text-[9px] font-mono bg-[#21262d] text-[#8b949e] border border-[#30363d]">
                      Bearer Token Required
                    </span>
                  ) : (
                    <span className="px-1.5 py-0.2 rounded text-[9px] font-mono text-[#6e7681]">Public</span>
                  )}
                </div>
              </div>

              <p className="text-xs text-[#8b949e] mt-1.5">{ep.description}</p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                {ep.sampleRequest && (
                  <div className="bg-[#161b22] p-2 rounded border border-[#21262d]">
                    <span className="text-[9px] font-mono text-[#6e7681] block mb-0.5">Request:</span>
                    <pre className="text-[10px] font-mono text-[#c9d1d9] overflow-x-auto">{ep.sampleRequest}</pre>
                  </div>
                )}

                {ep.sampleResponse && (
                  <div className="bg-[#161b22] p-2 rounded border border-[#21262d]">
                    <span className="text-[9px] font-mono text-[#6e7681] block mb-0.5">Response (200 OK):</span>
                    <pre className="text-[10px] font-mono text-[#3fb950] overflow-x-auto">{ep.sampleResponse}</pre>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Tab 4: Auth & Identity */}
      {activeBlueprintTab === 'auth' && (
        <div className="mt-4 space-y-3">
          <div className="bg-[#0d1117] rounded border border-[#30363d] p-3.5">
            <h4 className="text-xs font-semibold text-[#f0f6fc] font-mono uppercase mb-2">
              Authentication &amp; Session Management
            </h4>
            <p className="text-xs text-[#c9d1d9] leading-relaxed bg-[#161b22] p-2.5 rounded border border-[#21262d] mb-3">
              {blueprint.authStrategy.flowDescription}
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 mb-3">
              <div className="bg-[#161b22] p-2.5 rounded border border-[#21262d]">
                <span className="text-[10px] font-mono text-[#6e7681] block">Token Protocol:</span>
                <span className="text-xs font-mono text-[#f0f6fc]">{blueprint.authStrategy.tokenType}</span>
              </div>

              <div className="bg-[#161b22] p-2.5 rounded border border-[#21262d]">
                <span className="text-[10px] font-mono text-[#6e7681] block">Identity Provider:</span>
                <span className="text-xs font-mono text-[#f0f6fc]">{blueprint.authStrategy.method}</span>
              </div>
            </div>

            <div className="space-y-1">
              <span className="text-[10px] font-mono uppercase text-[#8b949e] font-semibold block">
                Security Controls
              </span>
              {blueprint.authStrategy.securityMeasures.map((measure, idx) => (
                <div
                  key={idx}
                  className="flex items-start space-x-2 text-xs text-[#c9d1d9] bg-[#161b22] p-2 rounded border border-[#21262d]"
                >
                  <Check className="w-3.5 h-3.5 text-[#3fb950] shrink-0 mt-0.5" />
                  <span>{measure}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Tab 5: Caching & Asynchronous Queue */}
      {activeBlueprintTab === 'caching' && (
        <div className="mt-4 grid grid-cols-1 lg:grid-cols-2 gap-3">
          {/* Caching Tiers */}
          <div className="bg-[#0d1117] rounded border border-[#30363d] p-3.5">
            <h4 className="text-xs font-semibold text-[#f0f6fc] font-mono uppercase mb-2.5">
              Multi-Tier Caching
            </h4>

            <div className="space-y-2">
              <div className="bg-[#161b22] p-2.5 rounded border border-[#21262d]">
                <span className="text-[10px] font-mono font-semibold text-[#58a6ff]">L1: Edge CDN Cache</span>
                <p className="text-xs text-[#c9d1d9] mt-0.5">{blueprint.cachingStrategy.cdnTier}</p>
              </div>

              <div className="bg-[#161b22] p-2.5 rounded border border-[#21262d]">
                <span className="text-[10px] font-mono font-semibold text-[#f778ba]">L2: Redis Key-Value Store</span>
                <p className="text-xs text-[#c9d1d9] mt-0.5">{blueprint.cachingStrategy.appTier}</p>
              </div>

              <div className="bg-[#161b22] p-2.5 rounded border border-[#21262d]">
                <span className="text-[10px] font-mono font-semibold text-[#3fb950]">L3: PostgreSQL Buffer Pool</span>
                <p className="text-xs text-[#c9d1d9] mt-0.5">{blueprint.cachingStrategy.databaseTier}</p>
              </div>
            </div>
          </div>

          {/* Asynchronous Queue */}
          <div className="bg-[#0d1117] rounded border border-[#30363d] p-3.5">
            <h4 className="text-xs font-semibold text-[#f0f6fc] font-mono uppercase mb-2.5">
              Task Queues &amp; Background Workers
            </h4>

            <div className="bg-[#161b22] p-2 rounded border border-[#21262d] mb-2">
              <span className="text-[10px] font-mono text-[#6e7681]">Broker:</span>
              <p className="text-xs font-mono text-[#f0f6fc]">{blueprint.asyncProcessing.queueSystem}</p>
            </div>

            <div className="space-y-1 mb-2.5">
              <span className="text-[10px] font-mono uppercase text-[#8b949e] font-semibold block">
                Background Jobs:
              </span>
              {blueprint.asyncProcessing.backgroundJobs.map((job, idx) => (
                <div
                  key={idx}
                  className="flex items-center space-x-2 text-xs text-[#c9d1d9] bg-[#161b22] p-1.5 rounded border border-[#21262d]"
                >
                  <div className="w-1.5 h-1.5 rounded-full bg-[#58a6ff]" />
                  <span>{job}</span>
                </div>
              ))}
            </div>

            <div className="p-2 rounded bg-[#161b22] border border-[#21262d] text-xs text-[#8b949e]">
              <span className="font-semibold text-[#f0f6fc]">Concurrency: </span>
              {blueprint.asyncProcessing.concurrencyModel}
            </div>
          </div>
        </div>
      )}

      {/* Tab 6: Phased Implementation Order */}
      {activeBlueprintTab === 'phases' && (
        <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">
          {blueprint.implementationPhases.map((phase) => (
            <div
              key={phase.phaseNumber}
              className="bg-[#0d1117] rounded border border-[#30363d] p-3.5 flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between pb-2 border-b border-[#21262d]">
                  <span className="px-1.5 py-0.2 rounded bg-[#21262d] text-[#8b949e] border border-[#30363d] text-[10px] font-mono font-semibold">
                    PHASE {phase.phaseNumber}
                  </span>
                  <span className="text-xs font-mono text-[#8b949e]">{phase.duration}</span>
                </div>

                <h4 className="text-xs font-semibold text-[#f0f6fc] mt-2 font-mono">{phase.title}</h4>

                <ul className="mt-2 space-y-1">
                  {phase.deliverables.map((item, idx) => (
                    <li key={idx} className="flex items-start space-x-2 text-xs text-[#c9d1d9]">
                      <span className="text-[#58a6ff] font-mono text-[10px] mt-0.5">›</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="mt-2.5 pt-2 border-t border-[#21262d] text-[11px] text-[#8b949e] font-mono">
                <span className="text-[#6e7681]">Milestone: </span>
                <span className="text-[#f0f6fc]">{phase.milestone}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Tab 7: Scalability */}
      {activeBlueprintTab === 'scalability' && (
        <div className="mt-4 space-y-2.5">
          {blueprint.scalabilityConsiderations.map((item, idx) => (
            <div
              key={idx}
              className="p-2.5 rounded bg-[#0d1117] border border-[#30363d] text-xs text-[#c9d1d9] flex items-start space-x-2"
            >
              <span className="font-mono text-[#58a6ff] text-xs font-bold">{idx + 1}.</span>
              <p className="leading-relaxed">{item}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
